lsi: false
safe: true
source: _images, _modules, _sources, _static
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
# Build settings
remote_theme: jekyll/minima

